/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.medicalpharm.view;

import br.com.medicalpharm.dao.RequisicoesProdutoDAO;
import br.com.medicalpharm.dao.UsuarioRequisitanteDAO;
import br.com.medicalpharm.model.UsuarioRequisitanteModel;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author willi
 */
public class UsuarioRequisitanteGerenciarGUI extends javax.swing.JFrame {

    /**
     * Creates new form UsuarioRequisitanteGerenciarGUI
     */
    public UsuarioRequisitanteGerenciarGUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        listarUsuarios();
    }
    //DefaultTableModel Jt_requisicoes = new DefaultTableModel(null, new String[]{"Código", "Nome", "Cpf"});
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        Jtable_usuarios = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciar Requisitantes");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                close(evt);
            }
        });

        Jtable_usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Cpf"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Jtable_usuarios.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(Jtable_usuarios);
        if (Jtable_usuarios.getColumnModel().getColumnCount() > 0) {
            Jtable_usuarios.getColumnModel().getColumn(0).setMinWidth(70);
            Jtable_usuarios.getColumnModel().getColumn(0).setMaxWidth(90);
            Jtable_usuarios.getColumnModel().getColumn(2).setMinWidth(120);
            Jtable_usuarios.getColumnModel().getColumn(2).setMaxWidth(140);
        }

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/exit.png"))); // NOI18N
        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/alterar_registro.gif"))); // NOI18N
        jButton2.setText("Editar Requisitante");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/novo_registro.gif"))); // NOI18N
        jButton3.setText("Novo Requisitante");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)))
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        UsuariosRequisitanteCadastroGUI abrir = new UsuariosRequisitanteCadastroGUI();
        this.setEnabled(false);
        abrir.telaPai = this;
        abrir.codigoCarregar();
        abrir.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(Jtable_usuarios.getSelectedRow() != -1){
            UsuariosRequisitanteCadastroGUI abrir = new UsuariosRequisitanteCadastroGUI();
            this.setEnabled(false);
            abrir.telaPai = this;
            abrir.codigo = Jtable_usuarios.getValueAt(Jtable_usuarios.getSelectedRow(), 0).toString();
            abrir.nome = Jtable_usuarios.getValueAt(Jtable_usuarios.getSelectedRow(), 1).toString();
            abrir.cpf = Jtable_usuarios.getValueAt(Jtable_usuarios.getSelectedRow(), 2).toString();
            abrir.update = true;
            abrir.codigoCarregar();
            abrir.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void close(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_close
        setVisible(false);
    }//GEN-LAST:event_close

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsuarioRequisitanteGerenciarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsuarioRequisitanteGerenciarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsuarioRequisitanteGerenciarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsuarioRequisitanteGerenciarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsuarioRequisitanteGerenciarGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Jtable_usuarios;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
    
    List<UsuarioRequisitanteModel> usuarios;
    public void listarUsuarios(){
        UsuarioRequisitanteDAO requi = new UsuarioRequisitanteDAO();
        usuarios = requi.listarUsuarios("%" + "" + "%");//tf_pesquisar_requisicao.getText().trim()
        mostraRequisicoes(usuarios);
    }
    public void mostraRequisicoes(List<UsuarioRequisitanteModel> requi){
        if(Jtable_usuarios.getRowCount() > 0){
            Jtable_usuarios.removeRowSelectionInterval(0, Jtable_usuarios.getRowCount());
        }
        RequisicoesProdutoDAO d = new RequisicoesProdutoDAO();        
         if (requi.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nenhum usuário encontrado");

        } else {

            DefaultTableModel row = (DefaultTableModel) Jtable_usuarios.getModel();
            for (int i = 0; i < requi.size(); i++) {
                row.addRow(new Object[]{requi.get(i).getCodigo_requisitante(),requi.get(i).getNome_requisitante(),requi.get(i).getCpf()});
            }
        }
    }
}
