/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.medicalpharm.view;

import br.com.medicalpharm.dao.VeiculoDAO;
import br.com.medicalpharm.model.VeiculoModel;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author willi
 */
public class VeiculoConsultar2GUI extends javax.swing.JFrame {

    /**
     * Creates new form VeiculoConsultar2GUI
     */
    public VeiculoConsultar2GUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        listarVeiculos("");        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jb_novo1 = new javax.swing.JButton();
        jb_ok = new javax.swing.JButton();
        jb_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel2.setText("Veiculos Encontrados");

        jTable1.setModel(Jt_veiculos        );
        jScrollPane1.setViewportView(jTable1);

        jb_novo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/novo_registro.gif"))); // NOI18N
        jb_novo1.setText("Novo");
        jb_novo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_novo1ActionPerformed(evt);
            }
        });

        jb_ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/ok.png"))); // NOI18N
        jb_ok.setText("OK");
        jb_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_okActionPerformed(evt);
            }
        });

        jb_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/exit.png"))); // NOI18N
        jb_cancelar.setText("Cancelar");
        jb_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jb_novo1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jb_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jb_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_novo1)
                    .addComponent(jb_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_novo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_novo1ActionPerformed
        VeiculoCadastrarEditar abrir = new VeiculoCadastrarEditar();
        abrir.telaPai2 = this;
        this.setEnabled(false);
        abrir.setVisible(true);
    }//GEN-LAST:event_jb_novo1ActionPerformed

    private void jb_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_okActionPerformed
        //        if (jTable1.getSelectedRow() == 1) {
           pegarVeiculo();
            //      }
    }//GEN-LAST:event_jb_okActionPerformed

    private void jb_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cancelarActionPerformed
            setVisible(false);
        //        if ((janelapai != null)) {
            //            janelapai.setEnabled(true);
            //            janelapai.setVisible(true);
            //            //telaCadNota.setStatusTela(false);
            //        }
        //
        //        if ((janelapai3 != null)) {
            //            janelapai3.setEnabled(true);
            //            janelapai3.setVisible(true);
            //        }
        // pegarUsuario();
    }//GEN-LAST:event_jb_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VeiculoConsultar2GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VeiculoConsultar2GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VeiculoConsultar2GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VeiculoConsultar2GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VeiculoConsultar2GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jb_cancelar;
    private javax.swing.JButton jb_novo1;
    private javax.swing.JButton jb_ok;
    // End of variables declaration//GEN-END:variables
    
    List<VeiculoModel> veiculos;
    DefaultTableModel Jt_veiculos = new DefaultTableModel(null, new String[]{"Código", "Descrição","Chassi","Placa"});
    public void listarVeiculos(String parametro){
        VeiculoDAO ve = new VeiculoDAO();
        while (Jt_veiculos.getRowCount() > 0) {
             Jt_veiculos.removeRow(0);
        }
        
        veiculos = ve.listarVeiculos(parametro,1);
        
        String[] campos = new String[]{null, null};
        for (int i = 0; i < veiculos.size(); i++) {
            Jt_veiculos.addRow(campos);
            Jt_veiculos.setValueAt(veiculos.get(i).getCodigo(),i,0);
            Jt_veiculos.setValueAt(veiculos.get(i).getDescricao(),i,1);
            Jt_veiculos.setValueAt(veiculos.get(i).getChassi(),i,2);
            Jt_veiculos.setValueAt(veiculos.get(i).getPlaca(),i,3);
        }
        
    }
    public VeiculoModel veiculo = new VeiculoModel();
    public RequisicaoNovaGUI  requiNova = null;
    public SaidaEstoqueGUI saidaEstoque = null;
    RequisicaoNovaGUI_Interface reInterface;
    SaidaEstoqueGUI_interface saInterface;
    public void pegarVeiculo(){
        veiculo.setCodigo(Integer.parseInt(Jt_veiculos.getValueAt(jTable1.getSelectedRow(),0).toString().trim()));
        veiculo.setDescricao(Jt_veiculos.getValueAt(jTable1.getSelectedRow(),1).toString().trim());
        veiculo.setChassi(Jt_veiculos.getValueAt(jTable1.getSelectedRow(),2).toString().trim());
        veiculo.setPlaca(Jt_veiculos.getValueAt(jTable1.getSelectedRow(),3).toString().trim());
        if(requiNova != null){
            reInterface.carregarVeiculo(veiculo);
        }else if(saidaEstoque != null){
            saInterface.carregarVeiculo(veiculo);
        }
        setVisible(false);
    }
    
    public void setRequisicaoNova(RequisicaoNovaGUI_Interface re){
        reInterface = re;
    }
    public void setSaidaEstoque(SaidaEstoqueGUI_interface sa){
        saInterface = sa;
    }
    
    


}
