/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.medicalpharm.view;
import br.com.medicalpharm.dao.ProdutoDAO;
import br.com.medicalpharm.dao.RequisicoesDAO;
import br.com.medicalpharm.model.ProdutoModel;
import br.com.medicalpharm.model.RequisicoesModel;
import br.com.medicalpharm.model.RequisicoesProdutoModel;
import br.com.medicalpharm.util.ItemDbGrid;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.DecimalFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author william
 */
public class RequisicaoNovaGUI extends javax.swing.JFrame {
    List<ProdutoModel> produtos;
    String nomeRequi;
    /**
     * Creates new form RequisicaoGUI
     */
    public RequisicaoNovaGUI(String nomeRequisitante) {
        initComponents();
        listaProduto();
        nomeRequi = nomeRequisitante;
       
        try {
          //  UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            // UIManager.setLookAndFeel("com.sun.java.swing.plaf.smoothmetal.SmoothmetalLookAndAndFeel");
            //UIManager.setLookAndFeel("com.birosoft.liquid.LiquidLookAndFeel");
            //UIManager.setLookAndFeel(seta_look);
         //   SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tf_pesquisar_produto = new javax.swing.JTextField();
        jb_buscar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jrb_apresentação = new javax.swing.JRadioButton();
        jrb_nome = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSpinner_qtd = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jb_sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Finalizar Requisição");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta"));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setText("Parâmetro");

        tf_pesquisar_produto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_pesquisar_produtoKeyPressed(evt);
            }
        });

        jb_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/ok.png"))); // NOI18N
        jb_buscar.setText("Ir");
        jb_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_buscarActionPerformed(evt);
            }
        });

        jButton1.setText("Lote");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jrb_apresentação.setSelected(true);
        jrb_apresentação.setText("Produto/Apresentação");

        jrb_nome.setText("Nome Comercial");

        jTable1 = new javax.swing.JTable();
        jTable1.setUpdateSelectionOnSort(false);
        jTable1.setVerifyInputWhenFocusTarget(false);
        jTable1.setDefaultEditor(Object.class, null);
        jTable1.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e){
                if(e.getClickCount() == 2){
                    alterar();

                }}});
                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [][] {

                    },
                    new String [] {
                        "Código", "Produto / Apresentação", "Unid", "Nome Comercial", "Grupo", "Sub-Grupo", "Est. Minimo", "Est. Ideal", "Est. Atual", "Ult. Preço", "orca"
                    }
                ) {
                    Class[] types = new Class [] {
                        java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
                    };
                    boolean[] canEdit = new boolean [] {
                        false, false, false, false, false, true, false, false, false, false, false
                    };

                    public Class getColumnClass(int columnIndex) {
                        return types [columnIndex];
                    }

                    public boolean isCellEditable(int rowIndex, int columnIndex) {
                        return canEdit [columnIndex];
                    }
                });
                jTable1.getTableHeader().setReorderingAllowed(false);
                jScrollPane1.setViewportView(jTable1);

                jLabel3.setText("Quantidade:");

                javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
                jPanel5.setLayout(jPanel5Layout);
                jPanel5Layout.setHorizontalGroup(
                    jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(tf_pesquisar_produto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jb_buscar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton1))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jrb_apresentação)
                                        .addGap(14, 14, 14)
                                        .addComponent(jrb_nome)
                                        .addGap(672, 672, 672)))
                                .addGap(6, 6, 6))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addContainerGap())
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinner_qtd, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                );
                jPanel5Layout.setVerticalGroup(
                    jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrb_apresentação)
                            .addComponent(jrb_nome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tf_pesquisar_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_buscar)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinner_qtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addContainerGap())
                );

                jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/gravar_registro.gif"))); // NOI18N
                jButton4.setText("Finalizar Requisição");
                jButton4.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton4ActionPerformed(evt);
                    }
                });

                jb_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/exit.png"))); // NOI18N
                jb_sair.setText("Cancelar");
                jb_sair.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jb_sairActionPerformed(evt);
                    }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jb_sair)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4)))
                        .addContainerGap())
                );
                layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jb_sair))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                pack();
            }// </editor-fold>//GEN-END:initComponents

    private void tf_pesquisar_produtoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_pesquisar_produtoKeyPressed
//        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {;
//            if(jrb_apresentação.isSelected()){
//                listaProduto();
//            } else {
//                listarComercial();
//            }
//        }
    }//GEN-LAST:event_tf_pesquisar_produtoKeyPressed

    private void jb_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_buscarActionPerformed
        if(jrb_apresentação.isSelected()){
            listaProduto();
        } else {
            listarComercial();
        }
    }//GEN-LAST:event_jb_buscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       // lote();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        cadastraRequisicao();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jb_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_sairActionPerformed
        this.setVisible(false);
        RequisicaoGerenciarGUI tela = new RequisicaoGerenciarGUI();
        tela.setEnabled(false);
    }//GEN-LAST:event_jb_sairActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        setVisible(false);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new RequisicaoNovaGUI("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner_qtd;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jb_buscar;
    private javax.swing.JButton jb_sair;
    private javax.swing.JRadioButton jrb_apresentação;
    private javax.swing.JRadioButton jrb_nome;
    private javax.swing.JTextField tf_pesquisar_produto;
    // End of variables declaration//GEN-END:variables
    
    private TelaPrincipal_Interface telaPrincipal;   
    public void alterar() {
         System.out.println("fazer requisicao");
    }
     
    public void listaProduto() {
        ProdutoDAO prod = new ProdutoDAO();
        produtos = prod.listarProduto("%" + tf_pesquisar_produto.getText().trim() + "%");        
        mostraProduto(produtos);
        
    } 
    public void mostraProduto(List<ProdutoModel> produtos) {
        ((DefaultTableModel) jTable1.getModel()).setRowCount(0);
        jTable1.updateUI();
        String preço = null;
        if (produtos.size() == 0) {
            JOptionPane.showMessageDialog(this, "Nenhum produto encontrado");

        } else {
            for (int i = 0; i < produtos.size(); i++) {
                ProdutoModel produto = new ProdutoModel();
                produto.setCod_produto(produtos.get(i).getCod_produto());
                produto.setNome_produto(produtos.get(i).getNome_produto());
                produto.setConcentraçao(produtos.get(i).getConcentraçao());
                produto.setEstoque(produtos.get(i).getEstoque());
                produto.setEstoque_ideal(produtos.get(i).getEstoque_ideal());
                produto.setEstoque_minimo(produtos.get(i).getEstoque_minimo());
                produto.setGrupo(produtos.get(i).getGrupo());
                produto.setUnidade(produtos.get(i).getUnidade());
                produto.setUltimo_preco(produtos.get(i).getUltimo_preco());
                produto.setSubGrupo(produtos.get(i).getSubGrupo());
                
                preço = String.valueOf(produtos.get(i).getUltimo_preco());
                preço = setPrecoFormat(preço);

                DefaultTableModel row = (DefaultTableModel) jTable1.getModel();
                
                //javax.swing.table.DefaultTableModel dtm = (javax.swing.table.DefaultTableModel) tbl.getModel();  
                //dtm.addRow(new Object[]{" ", " ", " ", " ", " ", " ", " ", " ", " "});  
    //cada " " para cada coluna da tabela e para um check box vc coloca true ou false (true marcado false marcado), configura o campo como boolean na tabela antes blz  
                ItemDbGrid hashDbGrid = new ItemDbGrid(produto, produto.getNome_produto());
                row.addRow(new Object[]{produto.getCod_produto(), hashDbGrid,produto.getUnidade().getSigla_unidade(), produto.getConcentraçao(), produto.getGrupo().getDesc_grupo(),produto.getSubGrupo().getDescSubGrupo(),
                produto.getEstoque_minimo(), produto.getEstoque_ideal(), produto.getEstoque(),preço,true});
            }
        }
    };
    
    public String setPrecoFormat(String preco) {
        DecimalFormat dFormat = new DecimalFormat();
        dFormat.applyPattern("R$ #0.00");
        return dFormat.format(getPrecoFormato(preco));
    }
    
    public Double getPrecoFormato(String preco) {
        Double precoFormatado = 0.0;
        try {
            preco = preco.replace("R", "");
            preco = preco.replace("$", "");
            preco = preco.replace(",", ".");
            preco = preco.replace(" ", "");
            precoFormatado = Double.parseDouble(preco.trim());

            //this.objFuncionario.setSalario(getSalarioFormat(jTSalario.getText())); pegar valor em double

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Valor Informado Incorreto!\nInforme um valor com o seguinte formato:\nEx: 100,00");
        }
        return precoFormatado;
    }

    public void cadastraRequisicao(){
        RequisicoesModel novaRequisicao = new RequisicoesModel();
        RequisicoesProdutoModel novaRequisicaoProduto = new RequisicoesProdutoModel();
        RequisicoesDAO cadastrar = new  RequisicoesDAO();
        TelaPrincipal janelaPai = new TelaPrincipal();
        try{
            if(jTable1.getSelectedRow() != -1){
                if(verificarQtd()){
                    novaRequisicao.setData_emissao(new java.sql.Date(new java.util.Date().getTime()));
                    novaRequisicao.setUsuario_requisitor(nomeRequi);
                    novaRequisicao.setUsuario_estoquista(RequisicoesModel.usuarioNome1);

                    novaRequisicaoProduto.setTipo("E");
                    novaRequisicaoProduto.setCodigoRequisicao(cadastrar.pegarUltimoID()+1);
                    novaRequisicaoProduto.setProduto(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
                    novaRequisicaoProduto.setQtd((Integer) jSpinner_qtd.getValue());
                    novaRequisicaoProduto.setData_devolucao(new java.sql.Date(new java.util.Date().getTime()));
                    novaRequisicaoProduto.setData_emissao(new java.sql.Date(new java.util.Date().getTime()));

                    
                    cadastrar.cadastrarNovaRequisicao(novaRequisicao, novaRequisicaoProduto);
                    int id = Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
                    ProdutoDAO novaQtd = new ProdutoDAO();
                    novaQtd.updateQuatidade((Integer) jSpinner_qtd.getValue(), id, "-","");
                    JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");
                    setVisible(false);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Selecione um produto");
            }
        }catch(Exception wx){
            System.out.println("Erro:"+wx);
        }
        
    }
     public boolean verificarQtd(){
        int qtdTabela = Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 8).toString());
        int qtdSpinner = (Integer) jSpinner_qtd.getValue();
        if(qtdTabela < qtdSpinner ){
            JOptionPane.showMessageDialog(null, "Valor Informado Incorreto!");
            return false;
        }
        if(qtdSpinner < 1){
            JOptionPane.showMessageDialog(null, "Valor Informado Incorreto Selecione um valor maior!");
            return false;
        }
        if(qtdTabela  < 1){
            JOptionPane.showMessageDialog(null, "Valor Informado Incorreto! selecione outro produto");
            return false;
        }
        
        
        return true;
     }  
     
     private void listarComercial() {
        ProdutoDAO prod = new ProdutoDAO();
        produtos = prod.listarProdutoComercial("%" + tf_pesquisar_produto.getText().trim() + "%");
        mostraProduto(produtos);
    }


}
