/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.medicalpharm.view;

import br.com.medicalpharm.dao.ProdutoDAO;
import br.com.medicalpharm.dao.RequisicoesProdutoDAO;
import br.com.medicalpharm.dao.UsuarioRequisitanteDAO;
import br.com.medicalpharm.model.RequisicoesProdutoModel;
import br.com.medicalpharm.model.UsuarioRequisitanteModel;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author willi
 */
public class RequisicaoGerenciarGUI extends javax.swing.JFrame {

    /**
     * Creates new form GerenciarRequisicaoGUI
     */
    public RequisicaoGerenciarGUI() {        
        initComponents();
        listarUsuarios();
        
       // buscarRequisicaoProduto();
        
    }    
       
    List<UsuarioRequisitanteModel> usuarios;
    
    DefaultTableModel Jt_requisicoes = new DefaultTableModel(null, new String[]{"Código", "Nome", "Cpf","Status"});
    DefaultTableModel Jt_requisicoesProduto = new DefaultTableModel(null, new String[]{"Codigo Requisição","Usuario Estoquista","Produto", "Qtd", "Qtd.devolvida", "Saldo"});
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jb_novo = new javax.swing.JButton();
        jb_sair = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jl_pesquisar_destino = new javax.swing.JLabel();
        jb_buscar = new javax.swing.JButton();
        tf_pesquisar_requisicao = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Jtable_usuarios = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        Jtable_requisicoesProdutos = new javax.swing.JTable();
        jSpinner_qtd = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        bt_devolver = new javax.swing.JButton();
        jb_novo1 = new javax.swing.JButton();
        jb_novo2 = new javax.swing.JButton();
        jb_novo3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciar Requisicões");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jb_novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/novo_registro.gif"))); // NOI18N
        jb_novo.setText("Devolução");
        jb_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_novoActionPerformed(evt);
            }
        });

        jb_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/exit.png"))); // NOI18N
        jb_sair.setText("Sair");
        jb_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_sairActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Consultas"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_pesquisar_destino.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jl_pesquisar_destino.setText("Nome:");
        jPanel1.add(jl_pesquisar_destino, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jb_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/ok.png"))); // NOI18N
        jb_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_buscarActionPerformed1(evt);
            }
        });
        jPanel1.add(jb_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, -1, -1));

        tf_pesquisar_requisicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_pesquisar_requisicaoActionPerformed(evt);
            }
        });
        jPanel1.add(tf_pesquisar_requisicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 520, 20));

        Jtable_requisicoesProdutos.setUpdateSelectionOnSort(false);
        Jtable_requisicoesProdutos.setVerifyInputWhenFocusTarget(false);
        Jtable_requisicoesProdutos.setDefaultEditor(Object.class, null);
        Jtable_usuarios.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e){
                if(e.getClickCount() == 1){
                    buscarRequisicaoProduto();
                }}});
                Jtable_usuarios.setModel(Jt_requisicoes);
                Jtable_usuarios.getTableHeader().setReorderingAllowed(false);
                jScrollPane2.setViewportView(Jtable_usuarios);

                Jtable_requisicoesProdutos.setModel(Jt_requisicoesProduto);
                jScrollPane3.setViewportView(Jtable_requisicoesProdutos);

                jLabel1.setText("Quantidade:");

                bt_devolver.setText("Devolver");
                bt_devolver.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        bt_devolverActionPerformed(evt);
                    }
                });

                jb_novo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/novo_registro.gif"))); // NOI18N
                jb_novo1.setText("Novo Usuário ");
                jb_novo1.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jb_novo1ActionPerformed(evt);
                    }
                });

                jb_novo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/novo_registro.gif"))); // NOI18N
                jb_novo2.setText("Editar Requisição");
                jb_novo2.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jb_novo2ActionPerformed(evt);
                    }
                });

                jb_novo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/novo_registro.gif"))); // NOI18N
                jb_novo3.setText("Nova Requisição");
                jb_novo3.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jb_novo3ActionPerformed(evt);
                    }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2)
                                    .addComponent(jScrollPane3)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(jb_novo1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jb_novo3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jb_novo2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jb_novo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jb_sair))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinner_qtd, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_devolver)))
                        .addGap(12, 12, 12))
                );
                layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jb_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_novo)
                            .addComponent(jb_novo1)
                            .addComponent(jb_novo2)
                            .addComponent(jb_novo3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinner_qtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(bt_devolver))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                pack();
            }// </editor-fold>//GEN-END:initComponents
    
    RequisicaoNovaGUI requisicaoNovaGUI;
    private void jb_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_novoActionPerformed
        if(Jtable_usuarios.getSelectedRow() != -1){
            requisicaoNovaGUI = new RequisicaoNovaGUI(Jtable_usuarios.getValueAt(Jtable_usuarios.getSelectedRow(), 1).toString());
            requisicaoNovaGUI.setVisible(true);
            this.setEnabled(true);
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um usuario");
        }
    }//GEN-LAST:event_jb_novoActionPerformed

    private void jb_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_sairActionPerformed
        setVisible(false);
        telaPrincipal.setStatusTela(true);
    }//GEN-LAST:event_jb_sairActionPerformed
    
    private void jb_buscarActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_buscarActionPerformed1
         listarUsuarios();
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_buscarActionPerformed1
    
    UsuariosRequisitanteCadastroGUI usuarioNovoGUI;
    private void jb_novo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_novo1ActionPerformed
        usuarioNovoGUI = new UsuariosRequisitanteCadastroGUI();
        usuarioNovoGUI.setVisible(true);
    }//GEN-LAST:event_jb_novo1ActionPerformed

    private void tf_pesquisar_requisicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_pesquisar_requisicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_pesquisar_requisicaoActionPerformed

    private void bt_devolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_devolverActionPerformed
      devolverProduto();
      buscarRequisicaoProduto();
    }//GEN-LAST:event_bt_devolverActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        setVisible(false);
        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    private void jb_novo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_novo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_novo2ActionPerformed

    private void jb_novo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_novo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_novo3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RequisicaoGerenciarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RequisicaoGerenciarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RequisicaoGerenciarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RequisicaoGerenciarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RequisicaoGerenciarGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Jtable_requisicoesProdutos;
    private javax.swing.JTable Jtable_usuarios;
    private javax.swing.JButton bt_devolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner_qtd;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton jb_buscar;
    private javax.swing.JButton jb_novo;
    private javax.swing.JButton jb_novo1;
    private javax.swing.JButton jb_novo2;
    private javax.swing.JButton jb_novo3;
    private javax.swing.JButton jb_sair;
    private javax.swing.JLabel jl_pesquisar_destino;
    private javax.swing.JTextField tf_pesquisar_requisicao;
    // End of variables declaration//GEN-END:variables
    private TelaPrincipal_Interface telaPrincipal;
    
    public void listarUsuarios(){
        UsuarioRequisitanteDAO requi = new UsuarioRequisitanteDAO();
        usuarios = requi.listarUsuarios("%" + tf_pesquisar_requisicao.getText().trim() + "%");//tf_pesquisar_requisicao.getText().trim()
        mostraRequisicoes(usuarios);
        
    }
    
    public void mostraRequisicoes(List<UsuarioRequisitanteModel> requi){
        RequisicoesProdutoDAO d = new RequisicoesProdutoDAO();
        while (Jt_requisicoes.getRowCount() > 0) {
            Jt_requisicoes.removeRow(0);
        }
         if (requi.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nenhum usuário encontrado");

        } else {


            String[] campos = new String[]{null, null};
            for (int i = 0; i < requi.size(); i++) {

                Jt_requisicoes.addRow(campos);

                Jt_requisicoes.setValueAt(requi.get(i).getCodigo_requisitante(), i, 0);
                Jt_requisicoes.setValueAt(requi.get(i).getNome_requisitante(), i, 1);
                Jt_requisicoes.setValueAt(requi.get(i).getCpf(), i, 2);               
                Jt_requisicoes.setValueAt(d.verificarStatus(requi.get(i).getNome_requisitante()), i, 3);

            }
        }
    }
    
    public void buscarRequisicaoProduto(){
        while ( Jt_requisicoesProduto.getRowCount() > 0) {
             Jt_requisicoesProduto.removeRow(0);
        }
        if(Jtable_usuarios.getSelectedRow() != -1){            
            RequisicoesProdutoDAO d = new RequisicoesProdutoDAO();
            
            List<RequisicoesProdutoModel> produtos = d.buscarRequisicaoProduto(Jt_requisicoes.getValueAt(Jtable_usuarios.getSelectedRow(), 1).toString().trim());
            String[] campos = new String[]{null, null};
            for (int i = 0; i < produtos.size(); i++) {                
                Jt_requisicoesProduto.addRow(campos);
                
                Jt_requisicoesProduto.setValueAt(produtos.get(i).getCodigoRequisicao(),i,0);
                Jt_requisicoesProduto.setValueAt(produtos.get(i).getUsuarioEstoquista(),i,1);
                Jt_requisicoesProduto.setValueAt(produtos.get(i).getProduto(),i, 2);
                Jt_requisicoesProduto.setValueAt(produtos.get(i).getQtd(),i, 3);
                Jt_requisicoesProduto.setValueAt(produtos.get(i).getQtdDevolvida(),i, 4);
                Jt_requisicoesProduto.setValueAt(produtos.get(i).getSaldo(),i, 5);
            }

        }
    }      
    
    
    public void devolverProduto(){
        RequisicoesProdutoModel novaRequisicaoProduto = new RequisicoesProdutoModel();
        
        if(Jtable_requisicoesProdutos.getSelectedRow() != -1){
            if(verificarQtd()){
                int codigo = Integer.parseInt(Jt_requisicoesProduto.getValueAt(Jtable_requisicoesProdutos.getSelectedRow(), 0).toString().trim());
                novaRequisicaoProduto.setTipo("D");
                novaRequisicaoProduto.setCodigoRequisicao(codigo);
                novaRequisicaoProduto.setProduto(Jt_requisicoesProduto.getValueAt(Jtable_requisicoesProdutos.getSelectedRow(), 2).toString().trim());
                novaRequisicaoProduto.setQtd((Integer) jSpinner_qtd.getValue());
                novaRequisicaoProduto.setData_devolucao(new java.sql.Date(new java.util.Date().getTime()));
                novaRequisicaoProduto.setData_emissao(new java.sql.Date(new java.util.Date().getTime()));

                RequisicoesProdutoDAO novaRequisicao = new RequisicoesProdutoDAO();
                novaRequisicao.cadastrarNovaRequisicaoProduto(novaRequisicaoProduto);
                ProdutoDAO novaQtd = new ProdutoDAO();
                novaQtd.updateQuatidade((Integer) jSpinner_qtd.getValue(), 0, "+",novaRequisicaoProduto.getProduto());
                JOptionPane.showMessageDialog(null, "Devolução concluida!");                
            }
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um produto");
        }
    }
    
    public boolean verificarQtd(){
        int qtdTabela = Integer.parseInt(Jt_requisicoesProduto.getValueAt(Jtable_requisicoesProdutos.getSelectedRow(), 5).toString().trim());
        int qtdSpinner =  (Integer) jSpinner_qtd.getValue(); 
        
         if(qtdSpinner < 1){
            JOptionPane.showMessageDialog(null, "Valor Informado Incorreto Selecione um valor maior!");
            return false;
        }
        if(qtdTabela  < 1){
            JOptionPane.showMessageDialog(null, "Valor Informado Incorreto! selecione outro produto");
            return false;
        }
        if(qtdTabela < qtdSpinner){
            return false;
        }
        return true;
    }
}
